### ISSUE TITLE
Paper Reference

### ISSUE THREAD

**Issue by anithselva** [yesheng-THU/GFGE#1]
Hello,

Could you please share with me the paper that this code repository is associated with? Unable to find it at this time.

Thanks

**Comment by yesheng-THU** [comment]
This repository contains training and inference code for the paper "Audio-Driven Stylized Gesture Generation with Flow-Based Model". This paper has just been accepted for ECCV 2022. Because we did not publish the paper on arXiv, it will take a few more months to see the full article on the ECCV website.
